### ISSUE TITLE
Take Type Of Id as parameter

### ISSUE THREAD

**Issue by maulik-modi** [patelprerak25/CygnetHRD#3]
https://github.com/patelprerak25/CygnetHRD/blob/27b623ca53688562e4e9b0f92ddb40f5935a5938/CygnetHRD.Application/Interfaces/IGenericRepository.cs#L8

Id type could be String, Integer , GUID  or Long

**Comment by patelprerak25** [comment]
Use an object as a datatype instead of a fixed int datatype for the Id field in IGenericRepository class.
