### ISSUE TITLE
Add new project - CygnetHRD.Persistence

### ISSUE THREAD

**Issue by maulik-modi** [patelprerak25/CygnetHRD#8]
Add DapperExtensions project as CygnetHRD.Persistence

Remove all attribute annotations from all places
Implement classmapper in repository project as shown here:
https://dapper-tutorial.net/knowledge-base/18361893/dapper-map-one-to-one-in-classmapper

**Comment by patelprerak25** [comment]
Create CygnetHRD.Persistence project into current solution and implement Dapper.Extention methods. Test and verify each method using swagger.
